name: Deploy to Pi
on:
  push:
    branches: [master]
    paths: ['frontend/**']

jobs:
  deploy:
    runs-on: self-hosted  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Pi
      run: |
        echo "🚀 Starting deployment on Pi..."
        /home/b/deploy-football.sh
        echo "✅ Deployment completed!"