name: Deploy Frontend to arrakis.house
on:
  push:
    branches: [master]
    paths: ["frontend/**"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies and build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Deploy to Pi Dokku
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          password: ${{ secrets.PI_PASSWORD }}
          script: |
            # Create temp directory for deployment
            rm -rf /tmp/football-deploy
            mkdir -p /tmp/football-deploy
            cd /tmp/football-deploy

            # Clone latest code
            git clone https://github.com/${{ github.repository }}.git .
            cd frontend

            # Install and build
            npm install
            npm run build

            # Create deployment archive
            cd build
            tar -czf ../../football-app.tar.gz .
            cd ../..

            # Ensure Dokku app exists with correct domain
            docker exec quirky_buck dokku apps:create football-frontend || true
            docker exec quirky_buck dokku domains:clear football-frontend
            docker exec quirky_buck dokku domains:add football-frontend football.arrakis.house

            # Copy build to Dokku container and deploy
            docker cp football-app.tar.gz quirky_buck:/tmp/
            docker exec quirky_buck bash -c '
              cd /tmp
              rm -rf deploy-temp
              mkdir deploy-temp
              cd deploy-temp
              tar -xzf ../football-app.tar.gz
              
              # Create a simple package.json for static serving
              cat > package.json << "EOF"
            {
              "name": "football-frontend",
              "version": "1.0.0",
              "scripts": {
                "start": "serve -s . -l ${PORT:-5000}"
              },
              "dependencies": {
                "serve": "^14.0.0"
              }
            }
            EOF
              
              # Deploy to Dokku
              dokku git:from-archive football-frontend .
              
              # Cleanup
              cd ..
              rm -rf deploy-temp football-app.tar.gz
            '

            # Cleanup on Pi
            rm -rf /tmp/football-deploy

            echo "🚀 Deployment completed!"
            echo "✅ App available at: https://football.arrakis.house"

            # Show deployment status
            docker exec quirky_buck dokku apps:list
            docker exec quirky_buck dokku urls football-frontend
